server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.153.129
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.153.129:3306/guli_cart
    username: root
    password: root
  task:
    execution:
      thread-name-prefix: cart-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60s
        queue-capacity: 5000
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 60
feign:
  sentinel:
    enabled: true
jwt:
  pubFilePath: F:\june\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: user-key
  expire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
